version: '3.8'

services:
  postgres:
    build: postgres
    image: custom-postgres:17
    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasktracker-network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/task_tracker_db
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - tasktracker-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - tasktracker-network

volumes:
  postgres_data:

networks:
  tasktracker-network:
    driver: bridge