version: '3.8'

services:
  backend:
    image: katusha2388/tasktracker-backend:latest
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/task_tracker_db

  frontend:
    image: katusha2388/tasktracker-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      API_BASE_URL: http://backend:8090

  postgres:
    image: katusha2388/tasktracker-postgres:latest
    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: